### ISSUE TITLE
Error log when create room

### ISSUE THREAD

**Issue by windmemory** [botorange/wechaty-puppet-macpro#1]
```shell
01:10:06 SILL REQUEST request()
01:10:07 SILL GRPC_GATEWAY createRoom => result.getToken() : puppet_macpro_26aab85fb7806cc5, this.token : puppet_macpro_26aab85fb7806cc5, data.code : 1, data: undefined
01:10:07 SILL MacproRoom createRoom res : [object Object]
01:10:07 VERB GRPC_GATEWAY on(room-create, function) registered
01:10:07 SILL PUPPET_MACPRO can not get room id, bcz no room-create event happened.
01:10:07 ERR Room create() exception: Error: can not get room id, bcz no room-create event happened.
    at PuppetMacpro.<anonymous> (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/src/puppet-macpro.ts:1292:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/dist/src/puppet-macpro.js:23:58)
(node:76028) UnhandledPromiseRejectionWarning: Error: can not get room id, bcz no room-create event happened.
    at PuppetMacpro.<anonymous> (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/src/puppet-macpro.ts:1292:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/dist/src/puppet-macpro.js:23:58)
(node:76028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:76028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
01:10:08 SILL GRPC_GATEWAY event code :  message
01:10:08 VERB PUPPET_MACPRO onProcessMessage()
01:10:08 SILL PUPPET_MACPRO message payload : {"my_account":"botorange2222","my_name":"彩虹桥","my_account_alias":"wxid_ztxmrdjbqcwp22","to_account":"botorange2222","to_account_alias":"wxid_ztxmrdjbqcwp22","to_name":"彩虹桥","g_number":"23696646520@chatroom","g_name":false,"content":"彩虹桥创建了群聊","content_type":1,"file_name":"","voice_len":0,"send_time":1567357808}
01:10:08 VERB PUPPET_MACPRO onMacproMessageFriendshipEvent({id=872810d2-4b81-44fe-b45f-4fa5dc33104d})
01:10:08 VERB Message static load(872810d2-4b81-44fe-b45f-4fa5dc33104d)
01:10:08 SILL Accessory #207<Message> constructor()
01:10:08 VERB Message constructor(872810d2-4b81-44fe-b45f-4fa5dc33104d) for class Message
01:10:08 VERB Message ready()
01:10:08 VERB Puppet messagePayload(872810d2-4b81-44fe-b45f-4fa5dc33104d)
01:10:08 SILL Puppet messagePayloadCache(872810d2-4b81-44fe-b45f-4fa5dc33104d) cache MISS
01:10:08 VERB PUPPET_MACPRO messageRawPayload(872810d2-4b81-44fe-b45f-4fa5dc33104d)
01:10:08 VERB PUPPET_MACPRO messagePayload([object Object])
01:10:08 SILL messageRawPayloadParser messageType 7
01:10:08 SILL Puppet messagePayload(872810d2-4b81-44fe-b45f-4fa5dc33104d) cache SET
01:10:08 SILL Accessory #208<Room> constructor()
01:10:08 SILL Room constructor(23696646520@chatroom)
01:10:08 VERB Room ready()
01:10:08 VERB Puppet roomPayload(23696646520@chatroom)
01:10:08 SILL Puppet roomPayloadCache(23696646520@chatroom) cache MISS
01:10:08 VERB PUPPET_MACPRO roomRawPayload(23696646520@chatroom)
(node:76028) UnhandledPromiseRejectionWarning: Error: can not get room payload by room id: 23696646520@chatroom
    at PuppetMacpro.<anonymous> (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/src/puppet-macpro.ts:1183:13)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/dist/src/puppet-macpro.js:23:58)
(node:76028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
01:10:09 SILL GRPC_GATEWAY event code :  room-member
01:10:09 VERB PUPPET_MACPRO room ID : 23696646520@chatroom has 2 members.
(node:76028) UnhandledPromiseRejectionWarning: Error: can not find room info by room id: 23696646520@chatroom
    at PuppetMacpro.<anonymous> (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/src/puppet-macpro.ts:272:15)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yuangao/git/xiaoju-bot/xiaoju-bot/node_modules/wechaty-puppet-macpro/dist/src/puppet-macpro.js:23:58)
(node:76028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by su-chang** [comment]
Thank u for point out this bug, we will fix it today.
