### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: tryRawPayload empty

### ISSUE THREAD

**Issue by wenh7788** [botorange/wechaty-puppet-macpro#13]
UnhandledPromiseRejectionWarning: Error: tryRawPayload empty
    at RequestClient.<anonymous> (/Users/zxc/workspace/company/tnWechatyMacpro/node_modules/wechaty-puppet-macpro/dist/src/utils/request.js:30:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zxc/workspace/company/tnWechatyMacpro/node_modules/wechaty-puppet-macpro/dist/src/utils/request.js:5:58)
(node:1038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

报错内容如上，我就是一个scan 和一个msg的监听 什么都没有做打印出这个报错

**Comment by su-chang** [comment]
这个是同步数据有问题，正在修复中

**Comment by ethanzyang** [comment]
@su-chang 遇到同样的问题，请问修复好了吗

**Comment by imhui** [comment]
@su-chang  遇到同样的问题，请问修复了吗？

**Comment by Claude-Ray** [comment]
+1

**Comment by ethanzyang** [comment]
@su-chang 请问修复了吗。 这个 bug 导致基本没法使用了

**Comment by su-chang** [comment]
抱歉哈，仍在处理中，请耐心等待

**Comment by su-chang** [comment]
@jerr123 @imhui @Claude-Ray @wenh7788 问题已经解决，可以继续跟进测试。
