### ISSUE TITLE
微信端退出Mac微信登录不会触发logout事件

### ISSUE THREAD

**Issue by wangtianxing** [botorange/wechaty-puppet-macpro#21]
版本信息：
wechaty：0.28.3
wechaty-puppet：0.16.1
wechaty-puppet-macpro：0.1.22

操作步骤：
1、启动登录机器人；
2、待机器人工作正常后，退出登录机器人，logout事件没有被触发，也不会结束node进程，过一会会报错；

错误信息：
(node:360) UnhandledPromiseRejectionWarning: Error: tryRawPayload empty
    at RequestClient.<anonymous> (J:\phpStudy\WWW\community-wechaty\node_modules\wechaty-puppet-macpro\dist\src\utils\request.js:30:39)
    at Generator.next (<anonymous>)
    at fulfilled (J:\phpStudy\WWW\community-wechaty\node_modules\wechaty-puppet-macpro\dist\src\utils\request.js:5:58)
(node:360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: tryRawPayload empty
    at RequestClient.<anonymous> (J:\phpStudy\WWW\community-wechaty\node_modules\wechaty-puppet-macpro\dist\src\utils\request.js:30:39)
    at Generator.next (<anonymous>)
    at fulfilled (J:\phpStudy\WWW\community-wechaty\node_modules\wechaty-puppet-macpro\dist\src\utils\request.js:5:58)

**Comment by su-chang** [comment]
Resolved already, please update the module wechaty-puppet-macpro and check it again. Thank you very much.
