### ISSUE TITLE
手机微信端退出Mac微信登录不会触发logout事件

### ISSUE THREAD

**Issue by makk24** [botorange/wechaty-puppet-macpro#32]
版本信息：
wechaty：0.28.3
wechaty-puppet-macpro：0.1.28

操作步骤：
1、启动登录机器人；
2、待机器人工作正常后，退出登录机器人，logout事件没有被触发，也不会结束node进程，会报错；

错误信息：
(node:5288) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at MacproUser.<anonymous> (D:\websites\macpro\node_modules\wechaty-puppet-macpro\dist\src\mac-api\user.js:71:21)
    at Generator.next (<anonymous>)
    at fulfilled (D:\websites\macpro\node_modules\wechaty-puppet-macpro\dist\src\mac-api\user.js:5:58)
(node:5288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by su-chang** [comment]
Resolved, please check it again, and close this issue. Thank you very much.
