### ISSUE TITLE
如果用户登出微信，'logout' 不会被触发，进程直接结束。

### ISSUE THREAD

**Issue by aishiqi** [botorange/wechaty-puppet-macpro#42]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: wechaty@0.28.3

- What is your wechaty-puppet-macpro version?
Answer: wechaty-puppet-macpro@0.1.30

wechaty-puppet-macpro@0.2.4 has another problem that, if I press log off from my mobile device, it neither trigger "logout" nor quit the process, if I restart the process, it does not show the QR code, instead, it says I am logged in, but actually it is not, and unable to receive messages.

- What is your node version? (run `node --version`)
Answer: v10.16.0

- What os are you using
Answer: Win10

## 2. Describe the bug

Give a clear and concise description of what the bug is.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
(node:11564) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at MacproContact.<anonymous> (E:\NodeJs\WeChatyTest\node_modules\wechaty-puppet-macpro\src\mac-api\contact.ts:100:13)
    at Generator.next (<anonymous>)
    at fulfilled (E:\NodeJs\WeChatyTest\node_modules\wechaty-puppet-macpro\dist\src\mac-api\contact.js:5:58)
(node:11564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Version 0.2.6 has resolved this issue, let's re-check it.
