### ISSUE TITLE
当前登录账户较多，请稍后再试

### ISSUE THREAD

**Issue by lhr0909** [botorange/wechaty-puppet-macpro#49]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-macpro
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: `0.28.3`

- What is your wechaty-puppet-macpro version?
Answer: `0.2.6`

- What is your node version? (run `node --version`)
Answer: `v10.18.0`

- What os are you using
Answer: Amazon Linux (a flavor of RedHat)

## 2. Describe the bug

Give a clear and concise description of what the bug is.

Cannot login. 

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. use token and create a simple script to login with puppet-macpro

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

Cannot login and bot is stuck doing nothing.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

See error log

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
05:12:48 INFO Config registering process.on("unhandledRejection") for development/debug
05:12:48 VERB Config constructor()
05:12:49 VERB Puppet constructor({"token":"puppet_macpro_1dfxxxxxxxxx"}) #0
05:12:49 VERB StateSwitch constructor(name=PuppetMacpro)
05:12:49 VERB MemoryCard constructor(undefined)
05:12:49 VERB MemoryCard getStorage() for storage type: N/A
05:12:49 VERB MemoryCard load() from storage: N/A
05:12:49 VERB MemoryCard load() no storage
05:12:49 VERB Puppet constructor() watchdog timeout set to 60 seconds
05:12:49 VERB HotImport callerResolve(., /home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet/dist/src/puppet.js)
05:12:49 SILL HotImport callerResolve() callsites() file=/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/hot-import/dist/src/hot-import.js, type=Object
05:12:49 SILL HotImport callerResolve() callsites() file=/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet/dist/src/puppet.js, type=null
05:12:49 SILL HotImport callerResolve() callsites() file=/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet-macpro/dist/src/puppet-macpro.js, type=null
05:12:49 SILL HotImport callerResolve() callerFile=/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet-macpro/dist/src/puppet-macpro.js
05:12:49 VERB Puppet constructor() childClassPath=/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet-macpro/dist/src
05:12:49 SILL Accessory #0<Wechaty> constructor()
05:12:49 VERB Wechaty contructor()
05:12:49 VERB StateSwitch constructor(name=Wechaty)
05:12:49 VERB StateSwitch constructor(name=WechatyReady)
05:12:49 VERB Wechaty on(scan, function) registered
05:12:49 VERB Wechaty onFunction(scan)
05:12:49 VERB Wechaty on(login, function) registered
05:12:49 VERB Wechaty onFunction(login)
05:12:49 VERB Wechaty on(logout, function) registered
05:12:49 VERB Wechaty onFunction(logout)
05:12:49 VERB Wechaty on(heartbeat, function) registered
05:12:49 VERB Wechaty onFunction(heartbeat)
05:12:49 VERB Puppet constructor() memory.load() done
05:12:49 VERB Wechaty on(message, function) registered
05:12:49 VERB Wechaty onFunction(message)
05:12:49 SILL Wechaty version() form development environment is not availble: ENOENT: no such file or directory, stat '/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty/dist/.git'
05:12:49 INFO Wechaty <Puppet#0<PuppetMacpro>()>(visa-bot) start() v0.28.3 is starting...
05:12:49 VERB Wechaty puppet: Puppet#0<PuppetMacpro>()
05:12:49 VERB Wechaty name: visa-bot
05:12:49 VERB Wechaty id: ck50k87w90000bkn74j8qh2l2
05:12:49 SILL StateSwitch <Wechaty> on() is false
05:12:49 SILL StateSwitch <WechatyReady> off() is true
05:12:49 VERB StateSwitch <WechatyReady> off(true) <- (true)
05:12:49 SILL StateSwitch <Wechaty> on() is false
05:12:49 VERB StateSwitch <Wechaty> on(pending) <- (false)
05:12:49 VERB MemoryCard constructor("visa-bot")
05:12:49 VERB MemoryCard getStorage() for storage type: N/A
05:12:49 VERB getStorage name: visa-bot, options: {"type":"file"}
05:12:49 VERB StorageFile constructor(visa-bot, ...)
05:12:49 VERB StorageBackend constructor(visa-bot, { type: file })
05:12:49 VERB MemoryCard load() from storage: StorageFile</home/ec2-user/visa-bot/rasa-wechat-server/visa-bot.memory-card.json>
05:12:49 VERB StorageFile load() from /home/ec2-user/visa-bot/rasa-wechat-server/visa-bot.memory-card.json
05:12:49 VERB MemoryCard load() file not exist, NOOP
05:12:49 VERB Wechaty initPuppet() Puppet#0<PuppetMacpro>()
05:12:49 VERB MemoryCard multiplex(puppet)
05:12:49 VERB MemoryCard static multiplex(MemoryCard<visa-bot>, puppet)
05:12:49 VERB MemoryCard constructor({"name":"visa-bot","multiplex":{"name":"puppet","parent":{"options":{"name":"visa-bot"},"name":"visa-bot","payload":{},"multiplexNameList":[],"storage":{"na
me":"visa-bot","options":{"type":"file"},"absFileName":"/home/ec2-user/visa-bot/rasa-wechat-server/visa-bot.memory-card.json"}}}})
05:12:49 VERB PuppetManager resolve({puppet: Puppet#0<PuppetMacpro>(), puppetOptions: undefined})
05:12:49 VERB PuppetManager resolveInstance(Puppet#0<PuppetMacpro>())
05:12:49 VERB Puppet setMemory()
05:12:49 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetMacpro>(visa-bot))
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(login) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(logout) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(message) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(scan) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(dong) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(error) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(ready) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(reset) registered
05:12:49 VERB Wechaty initPuppetEventBridge() puppet.on(watchdog) registered
05:12:49 VERB Wechaty initAccessory(Puppet#0<PuppetMacpro>(visa-bot))
05:12:49 SILL Accessory <Contact> static set wechaty = "Wechaty#ck50k87w90000bkn74j8qh2l2<Puppet#0<PuppetMacpro>(visa-bot)>(visa-bot)"
05:12:49 SILL Accessory <ContactSelf> static set wechaty = "Wechaty#ck50k87w90000bkn74j8qh2l2<Puppet#0<PuppetMacpro>(visa-bot)>(visa-bot)"
05:12:49 SILL Accessory <Friendship> static set wechaty = "Wechaty#ck50k87w90000bkn74j8qh2l2<Puppet#0<PuppetMacpro>(visa-bot)>(visa-bot)"
05:12:49 SILL Accessory <Message> static set wechaty = "Wechaty#ck50k87w90000bkn74j8qh2l2<Puppet#0<PuppetMacpro>(visa-bot)>(visa-bot)"
05:12:49 SILL Accessory <Room> static set wechaty = "Wechaty#ck50k87w90000bkn74j8qh2l2<Puppet#0<PuppetMacpro>(visa-bot)>(visa-bot)"
05:12:49 SILL Accessory <RoomInvitation> static set wechaty = "Wechaty#ck50k87w90000bkn74j8qh2l2<Puppet#0<PuppetMacpro>(visa-bot)>(visa-bot)"
05:12:49 SILL Accessory <Contact> static set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL Accessory <ContactSelf> static set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL Accessory <Friendship> static set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL Accessory <Message> static set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL Accessory <Room> static set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL Accessory <RoomInvitation> static set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL Accessory <Wechaty> set puppet = "Puppet#0<PuppetMacpro>(visa-bot)"
05:12:49 SILL PUPPET_MACPRO start()
05:12:49 SILL StateSwitch <PuppetMacpro> on() is false
05:12:49 VERB StateSwitch <PuppetMacpro> on(pending) <- (false)
05:12:49 SILL GRPC_GATEWAY notify(getLoginUserInfo, undefined)
05:12:49 VERB GRPC_GATEWAY on(reconnect, function) registered
05:12:49 VERB GRPC_GATEWAY on(heartbeat, function) registered
05:12:49 VERB GRPC_GATEWAY on(scan, function) registered
05:12:49 VERB GRPC_GATEWAY on(login, function) registered
05:12:49 VERB GRPC_GATEWAY on(logout, function) registered
05:12:49 VERB GRPC_GATEWAY on(not-login, function) registered
05:12:49 VERB GRPC_GATEWAY on(message, function) registered
05:12:49 VERB GRPC_GATEWAY on(contact-list, function) registered
05:12:49 VERB GRPC_GATEWAY on(contact-info, function) registered
05:12:49 VERB GRPC_GATEWAY on(room-list, function) registered
05:12:49 VERB GRPC_GATEWAY on(room-info, function) registered
05:12:49 VERB GRPC_GATEWAY on(room-qrcode, function) registered
05:12:49 VERB GRPC_GATEWAY on(room-join, function) registered
05:12:49 VERB GRPC_GATEWAY on(room-member, function) registered
05:12:49 VERB GRPC_GATEWAY on(new-friend, function) registered
05:12:49 VERB GRPC_GATEWAY on(add-friend, function) registered
05:12:49 VERB GRPC_GATEWAY on(del-friend, function) registered
05:12:49 VERB GRPC_GATEWAY on(add-friend-before-accept, function) registered
05:12:49 SILL StateSwitch <PuppetMacpro> on() is pending
05:12:49 VERB StateSwitch <PuppetMacpro> on(true) <- (pending)
05:12:49 VERB Wechaty on(heartbeat, function) registered
05:12:49 VERB Wechaty onFunction(heartbeat)
05:12:49 SILL StateSwitch <Wechaty> on() is pending
05:12:49 VERB StateSwitch <PuppetMacpro> on(true) <- (pending)
05:12:49 VERB Wechaty on(heartbeat, function) registered
05:12:49 VERB Wechaty onFunction(heartbeat)
05:12:49 SILL StateSwitch <Wechaty> on() is pending
05:12:49 VERB StateSwitch <Wechaty> on(true) <- (pending)
05:12:49 SILL GRPC_GATEWAY event code :  not-login
05:12:49 SILL GRPC_GATEWAY throttleQueue emit heartbeat.
05:12:49 SILL Wechaty memoryCheck() free: 342 MB, require: 4 MB
05:12:49 VERB PUPPET_MACPRO 
      ======================================
               grpc on not-login
      ======================================
      
05:12:49 VERB MemoryCard <puppet> get(WECHATY_PUPPET_MACPRO)
05:12:49 SILL MAC_API_USER getWeChatQRCode(first login)
05:12:49 SILL REQUEST request()
05:12:50 SILL GRPC_GATEWAY 
      ===============================================================
      API Name : loginScanQRCode
      Request data : {"extend":"puppet_macpro_1dfxxxxxxxxxxx"}
      Response data : {"code":0,"msg":"当前登录账户较多，请稍后再试！"}
      ===============================================================
      
05:12:50 SILL GRPC_GATEWAY loginScanQRCode request error data : { code: 0, msg: '当前登录账户较多，请稍后再试！' }
05:12:50 SILL MAC_API_USER res : undefined
05:12:50 ERR Config ###########################
05:12:50 ERR Config unhandledRejection: TypeError: Cannot read property 'task_id' of undefined [object Promise]
05:12:50 ERR Config ###########################
05:12:50 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'task_id' of undefined)
Config TypeError: Cannot read property 'task_id' of undefined
    at MacproUser.<anonymous> (/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet-macpro/dist/src/mac-api/user.js:37:21)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ec2-user/visa-bot/rasa-wechat-server/node_modules/wechaty-puppet-macpro/dist/src/mac-api/user.js:5:58)
(node:27632) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Already resolved, thank you for your issue.
